# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.define "master" do |subconfig|
        subconfig.vm.box = "generic/ubuntu2004"
        subconfig.vm.hostname = "master"

        # Configura la red como puente con el adaptador seleccionado
        subconfig.vm.network "public_network", bridge: "Realtek RTL8852AE WiFi 6 802.11ax PCIe Adapter"

        # Configuración específica para VirtualBox
        subconfig.vm.provider "virtualbox" do |vb|
            vb.name = "ubuntu_cluster_master"  # Nombre de la VM en VirtualBox
            vb.memory = 2048  # Configura la memoria RAM
            vb.cpus = 2       # Configura el número de CPUs
        end
        # Especificar el usuario SSH y la nueva ruta de la clave privada
        subconfig.ssh.username = "vagrant"
        subconfig.ssh.private_key_path = "~/insecure_private_key"
        #subconfig.ssh.password = "vagrant"
        subconfig.ssh.insert_key = false  # Desactiva la inserción de la clave privada
        # Aprovisionamiento con Ansible
        subconfig.vm.provision "ansible" do |a|
            a.compatibility_mode = "auto"
            a.verbose = "v"
            a.playbook = "master_playbook.yaml"
        end
    end
end
